# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
