# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GWENT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GWENT.Card')),
            ],
        ),
        migrations.RemoveField(
            model_name='deck',
            name='deck',
        ),
        migrations.AddField(
            model_name='amount',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GWENT.Deck'),
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(through='GWENT.Amount', to='GWENT.Card'),
        ),
    ]
